### ISSUE TITLE
FixFileAndDirPermissions default mask sets file permissions to writable by any user.

### ISSUE THREAD

**Issue by rawrly** [igorhrcek/wp-cli-secure-command#38]
**Describe the bug**

The Default permission mask used in FixFileAndDirPermissions sets files to 0666, which would allow any user to write to files in the WordPress installation.

I would recommend a file mask of 0644, which would only allow the owner of the file to write to it, and still allows read access to all other users.

**To Reproduce**

Run  `wp secure fix-permissions`

**Expected behavior**

I suspect the intended behavior of this function would be to set the mask to 0644, which is rw-r--r-- or sets files readable by any user, but writable by only the owner of the file.

**Comment by DanielRuf** [comment]
644 should be always the default and there should be two command parameters for adjusting these. Also keep mind of symlinks (I see no symlink check).

**Comment by DanielRuf** [comment]
Done at https://github.com/wp-cli-secure/wp-cli-secure-command (https://github.com/wp-cli-secure/wp-cli-secure-command/commit/6d54e85878bbc19803595845741722320981732a).

**Comment by igorhrcek** [comment]
Agreed, will be fixed.
