### ISSUE TITLE
Error: Package installation failed.

### ISSUE THREAD

**Issue by vayurobins** [igorhrcek/wp-cli-secure-command#43]
**Describe the bug**
I tried to install the package, just copied the line `wp package install git@github.com:igorhrcek/wp-cli-secure-command.git` and inserted it into iTerm. The error i got was:

`Warning: Package name mismatch...Updating from git name 'igorhrcek/wp-cli-secure-command' to composer.json name 'igor/wp_cli_secure_command'.
Installing package igor/wp_cli_secure_command (dev-master)
Updating /Users/xxxx/.wp-cli/packages/composer.json to require the package...
Registering git@github.com:igorhrcek/wp-cli-secure-command.git as a VCS repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Warning: The 'https://api.github.com/repos/igorhrcek/wp-cli-secure-command' URL could not be accessed: HTTP/1.1 400 Bad Request

---
Error: Package installation failed.
Reverted composer.json.`

 - OS: MacOS Monterey

**Comment by igorhrcek** [comment]
That sounds like a GitHub issue.

**Comment by vayurobins** [comment]
Hi @igorhrcek, I'm not sure what to do with that, what do you mean? :-)

**Comment by DanielRuf** [comment]
Which composer version is used?

**Comment by vayurobins** [comment]
Thanks for asking @DanielRuf :-)
I am using Composer version 2.3.4.
