### ISSUE TITLE
Repeated and incorrectly formatted rules in .htaccess causing errors

### ISSUE THREAD

**Issue by rafaucau** [igorhrcek/wp-cli-secure-command#44]
**Describe the bug**
Repeated and incorrectly formatted rules in .htacces causing errors.

**To Reproduce**
1. Run `wp secure block-access sensitive-files`
2. Check `.htaccess` file
3. Each rule is repeated 4 times

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/162844297-a8f14de6-510e-4c3a-8ea3-7d3f648c2f40.png)

**Comment by igorhrcek** [comment]
Hi @rafaucau thank you for submitting the bug.

This issue has been resolved in the following commit:
https://github.com/igorhrcek/wp-cli-secure-command/commit/eb2348c57ad892a519b8280b9e4c124e2d1f908d
