### ISSUE TITLE
Implement a CICD workflow for automated testing 

### ISSUE THREAD

**Issue by igorhrcek** [igorhrcek/wp-cli-secure-command#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We need to develop custom CICD workflow for automated execution of tests using GitHub Actions

**Describe alternatives you've considered**
None

**Additional context**
We need to build Docker containers that will use both Apache and nginx to run WordPress. The reason for this is because we are doing integration tests for actual .htaccess and nginx rules that are deployed with our commands.

So to do so, we probably will have to modify official WordPress containers and add WP CLI and then to make a full workflow for performing tests.

**Comment by DanielRuf** [comment]
I've started creating a CI setup - so far there is still much to do to make it really usable for users. See also https://github.com/igorhrcek/wp-cli-secure-command/issues/37#issuecomment-1086603248

**Comment by igorhrcek** [comment]
It's almost finished, I think that I will push the code this week.
