### ISSUE TITLE
Refactor existing command that are blocking PHP execution in various places

### ISSUE THREAD

**Issue by igorhrcek** [igorhrcek/wp-cli-secure-command#9]
**Is your feature request related to a problem? Please describe.**
There are a few commands that are doing the same thing (blocking PHP execution) on various paths and instead of having 4 separate commands, we might have one.

**Describe the solution you'd like**
Remove all existing block-php commands and replace it with only one that will accept arguments?

**Describe alternatives you've considered**
None

**Additional context**
For example, instead of:
```
wp secure block_php_exution_in_uploads
```

we should have:
```
wp secure blockphp --locations=uploads,themes,plugins,wp-includes
```

**Comment by janw-me** [comment]
I'll take it.
